spring:
  application:
    name: ifsae

  # Timezone Setting
  jackson:
    time-zone: Asia/Seoul

  # Import .env file
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${PROFILE}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  data:
    redis:
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2

  security:
    user:
      name: admin
      password: admin
      roles: USER, ADMIN

server:
  port: ${SERVER_PORT}

jwt:
  secret:
    key: ${JWT_KEY}
  access:
    expiration: ${ACCESS_TOKEN_EXPIRATION_PERIOD}
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRATION_PERIOD}

cloud:
  aws:
    region:
      static: ap-southeast-2
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}

springdoc:
  swagger-ui:
    path: /
    enabled: true
    groups-order: asc
    tags-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  override-with-generic-response: false
  model-and-view-allowed: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8

video:
  chunk-size: 1048576
  ffmpeg:
    video-codec: h264
    audio-codec: mp3
    crf: 42
    audio-bitrate: 256k
    scale: 1280:720
  emitter:
    event-name: progress
  directory:
    s3: video/