spring:
  config:
    active:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      max-lifetime: 177000

  #    sql:
  #    init:
  #      mode: always
  #      data-locations: classpath:sql/data_prod.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  #    defer-datasource-initialization: true
  #    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      lettuce:
        pool:
          max-active: 5
          max-idle: 5
          min-idle: 2

server:
  port: ${PROD_SERVER_PORT}

frontend:
  url: ${FRONTEND_URL}