export enum ENDPOINT {
  // AUTH
  LOGIN = 'api/auth/signin',
}

export enum HTTP_STATUS {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  CONFLICT = 409,
  CONTENT_TOO_LARGE = 413,
  INTERNAL_SERVER_ERROR = 500,
}
